# Generated by Django 6.0.2 on 2026-02-26 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConstraintConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constraint_type', models.CharField(max_length=100, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('is_hard', models.BooleanField(default=True)),
                ('weight', models.IntegerField(default=1)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['constraint_type'],
            },
        ),
        migrations.CreateModel(
            name='ShiftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_type_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('start_time', models.TimeField()),
                ('duration_hours', models.FloatField()),
                ('is_undesirable', models.BooleanField(default=False)),
                ('min_workers', models.IntegerField(default=1)),
                ('max_workers', models.IntegerField(blank=True, null=True)),
                ('workers_required', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('applicable_days', models.JSONField(blank=True, null=True)),
                ('required_attributes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('group', models.CharField(blank=True, default='', max_length=100)),
                ('worker_type', models.CharField(blank=True, default='', max_length=100)),
                ('fte', models.FloatField(default=1.0)),
                ('is_active', models.BooleanField(default=True)),
                ('restricted_shifts', models.JSONField(blank=True, default=list)),
                ('preferred_shifts', models.JSONField(blank=True, default=list)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('period_length_days', models.IntegerField(default=7)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shift_types', models.ManyToManyField(blank=True, to='core.shifttype')),
                ('workers', models.ManyToManyField(blank=True, to='core.worker')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SolverRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result_json', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('progress_percent', models.IntegerField(default=0)),
                ('schedule_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solver_runs', to='core.schedulerequest')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('preference', models.IntegerField(default=0)),
                ('shift_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.shifttype')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='core.worker')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shifttype')),
                ('solver_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.solverrun')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.worker')),
            ],
            options={
                'ordering': ['date', 'worker'],
            },
        ),
    ]
