# Generated by Django 6.0.2 on 2026-02-26 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolverSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_limit_seconds', models.IntegerField(default=60)),
                ('num_search_workers', models.IntegerField(default=8)),
                ('optimality_tolerance', models.FloatField(default=0.0)),
                ('log_search_progress', models.BooleanField(default=True)),
                ('schedule_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solver_settings', to='core.schedulerequest')),
            ],
            options={
                'verbose_name_plural': 'solver settings',
            },
        ),
    ]
