# Generated by Django 6.0.2 on 2026-02-26 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_solversettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('request_type', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative')], default='negative', max_length=10)),
                ('priority', models.IntegerField(default=1)),
                ('is_hard', models.BooleanField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_requests', to='core.schedulerequest')),
                ('shift_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_requests', to='core.shifttype')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_requests', to='core.worker')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
