# Generated by Django 6.0.2 on 2026-06-03 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_solverrun_progress_json_cancelled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='preference',
        ),
        migrations.RemoveField(
            model_name='shifttype',
            name='max_workers',
        ),
        migrations.RemoveField(
            model_name='shifttype',
            name='min_workers',
        ),
        migrations.RemoveField(
            model_name='shifttype',
            name='required_attributes',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='fte',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='preferred_shifts',
        ),
    ]
